### ISSUE TITLE
Uninstalled but still changing wallpaper

### ISSUE THREAD

**Issue by rohit-gandhe** [cricklet/Auto-Wallpaper-for-reddit-#2]
There seems to be a service running in the background that doesn't stop after uninstalling the app

**Comment by cricklet** [comment]
Ouch, that's no good. Unfortunately, I'm no longer supporting the app-- I actually took it down from the Play Store.

Does restarting solve the problem?

**Comment by rohit-gandhe** [comment]
Restarting doesn't solve the problem. Is there a service that is running in the background that I can look for?

**Comment by rohit-gandhe** [comment]
Maybe put it back on the play store so I have an option to install and uninstall again :)

**Comment by cricklet** [comment]
Haha, good troubleshooting. I've republished it. I'm taking it down on Thursday, so you have a day to do your worst :)

Sorry for the trouble. I can't imagine how this happened. But considering that Android's done some pretty serious changes in the last 2-3 years (which is when I first wrote this-- the git history is fake haha), I suppose it's not that surprising that something broke hellishly.

**Comment by rohit-gandhe** [comment]
That did the trick!! Thanks Kenrick!!
